LDIR = src/main

# Sources and objects
SOURCES += $(LDIR)/OceanWave3D.f90
SOURCES += $(LDIR)/OceanWave3DT0Setup.f90 
SOURCES += $(LDIR)/OceanWave3DTakeATimeStep.f90
SOURCES += $(LDIR)/rhsFreeSurface3D.f90
SOURCES += $(LDIR)/rhsLinearFreeSurface3D.f90
SOURCES += $(LDIR)/TestCodeDucrozet1.f90
SOURCES += $(LDIR)/TestCodeDucrozet2.f90
