LDIR = src/utilities

# Sources and objects
SOURCES += $(LDIR)/DetectBreaking.f90
SOURCES += $(LDIR)/GASDEV.f90
SOURCES += $(LDIR)/JONSWAP_spectrum.f90
SOURCES += $(LDIR)/PM_spectrum.f90
SOURCES += $(LDIR)/RAN1_b.f90
SOURCES += $(LDIR)/build_coeff.f90
SOURCES += $(LDIR)/distdot.f90
SOURCES += $(LDIR)/eqns.f
SOURCES += $(LDIR)/fdwvnum.f90
SOURCES += $(LDIR)/init.f
SOURCES += $(LDIR)/LocalSmoothing2D.f90
SOURCES += $(LDIR)/lubksb.f90
SOURCES += $(LDIR)/ludcmp.f90
SOURCES += $(LDIR)/ran1.f90
SOURCES += $(LDIR)/random_wave_signal.f90
SOURCES += $(LDIR)/random_wave_signal_3D.f90
SOURCES += $(LDIR)/savgol.f90
SOURCES += $(LDIR)/stream_func_coeffs.f
SOURCES += $(LDIR)/stream_func_set_up.f90
SOURCES += $(LDIR)/stream_func_wave_finite.f
