LDIR = src/timeintegration

# Sources and objects
SOURCES += $(LDIR)/DifferentiationsFreeSurfacePlane.f90
SOURCES += $(LDIR)/Runge_Kutta_4.f90
SOURCES += $(LDIR)/Runge_Kutta_45.f90
SOURCES += $(LDIR)/timeintegration_fsbc.f90
