LDIR = src/analyticalsolutions

# Sources and objects
SOURCES += $(LDIR)/beachgen2.f90 
SOURCES += $(LDIR)/beachgen3D.f90
SOURCES += $(LDIR)/bottomBerkoff.f90
SOURCES += $(LDIR)/bottomWhalin.f90
SOURCES += $(LDIR)/bottomVincent.f90
SOURCES += $(LDIR)/disper.f90
SOURCES += $(LDIR)/linearstandingwave2D.f90
SOURCES += $(LDIR)/submergedbar2D.f90
SOURCES += $(LDIR)/nonlinearstandingwave1D.f90
