LDIR = /src/variabledefs

# Local sources and objects
SOURCES += $(LDIR)/precision.f90
SOURCES += $(LDIR)/constants.f90
SOURCES += $(LDIR)/datatypes.f90
SOURCES += $(LDIR)/HSL_LU.f90
SOURCES += $(LDIR)/OFmodule.f90
SOURCES += $(LDIR)/globalvariables.f90
SOURCES += $(LDIR)/pdamp_CSR.f90
SOURCES += $(LDIR)/SPK.f90
